server:
  port: 8080

spring:
  application:
    name: silsonfit-api

  profiles:
    active: dev

jwt:
  access-token-expiration: 3600000      # 60분
  refresh-token-expiration: 1209600000  # 14일

kakao:
  user-info-uri: https://kapi.kakao.com/v2/user/me

edi:
  public-api:
    endpoint: https://apis.data.go.kr/B551182/mdfeeCrtrInfoService
    service-key: ${EDI_PUBLIC_API_SERVICE_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n"
