spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/silsonfit
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: OFF