spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/silsonfit
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  ai:
    retry:
      max-attempts: 1 # 실패 시 재시도 횟수 제한
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.1

jwt:
  secret: ${JWT_SECRET}

aws:
  s3:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: silsonfit-storage

edi:
  public-api:
    service-key: ${EDI_PUBLIC_API_SERVICE_KEY}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: OFF
